# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = komoxplore2

HEADERS = \
   $$PWD/rai/rai/Algo/algos.h \
   $$PWD/rai/rai/Algo/ann.h \
   $$PWD/rai/rai/Algo/astar.h \
   $$PWD/rai/rai/Algo/cma.h \
   $$PWD/rai/rai/Algo/dataNeighbored.h \
   $$PWD/rai/rai/Algo/eigenValues.h \
   $$PWD/rai/rai/Algo/gaussianProcess.h \
   $$PWD/rai/rai/Algo/gpOp.h \
   $$PWD/rai/rai/Algo/hungarian.h \
   $$PWD/rai/rai/Algo/kalman.h \
   $$PWD/rai/rai/Algo/MLcourse.h \
   $$PWD/rai/rai/Algo/priorityQueue.h \
   $$PWD/rai/rai/Algo/rrt.h \
   $$PWD/rai/rai/Algo/spline.h \
   $$PWD/rai/rai/Control/retired/dynamicMovementPrimitives.h \
   $$PWD/rai/rai/Control/retired/GamepadControlThread.h \
   $$PWD/rai/rai/Control/retired/taskControl-18-09-06.h \
   $$PWD/rai/rai/Control/retired/taskController-17-02-09.h \
   $$PWD/rai/rai/Control/retired/TaskControllerModule-17-02-10.h \
   $$PWD/rai/rai/Control/retired/taskSpaceController_danny.h \
   $$PWD/rai/rai/Control/ctrlMsg.h \
   $$PWD/rai/rai/Control/gamepad2tasks.h \
   $$PWD/rai/rai/Control/gravityCompensation.h \
   $$PWD/rai/rai/Control/RTControllerSimulation.h \
   $$PWD/rai/rai/Control/taskControl.h \
   $$PWD/rai/rai/Control/TaskControlThread.h \
   $$PWD/rai/rai/Control/teleop2tasks.h \
   $$PWD/rai/rai/Core/lapack/blaswrap.h \
   $$PWD/rai/rai/Core/lapack/cblas.h \
   $$PWD/rai/rai/Core/lapack/clapack.h \
   $$PWD/rai/rai/Core/lapack/lapacke.h \
   $$PWD/rai/rai/Core/retired/algos.h \
   $$PWD/rai/rai/Core/retired/cygwin_compat.h \
   $$PWD/rai/rai/Core/retired/module.h \
   $$PWD/rai/rai/Core/retired/qt_integration.h \
   $$PWD/rai/rai/Core/retired/registry.h \
   $$PWD/rai/rai/Core/retired/thread.h \
   $$PWD/rai/rai/Core/retired/util.h \
   $$PWD/rai/rai/Core/array.h \
   $$PWD/rai/rai/Core/graph.h \
   $$PWD/rai/rai/Core/thread.h \
   $$PWD/rai/rai/Core/util.h \
   $$PWD/rai/rai/Geo/ccd/alloc.h \
   $$PWD/rai/rai/Geo/ccd/ccd.h \
   $$PWD/rai/rai/Geo/ccd/compiler.h \
   $$PWD/rai/rai/Geo/ccd/config.h \
   $$PWD/rai/rai/Geo/ccd/dbg.h \
   $$PWD/rai/rai/Geo/ccd/list.h \
   $$PWD/rai/rai/Geo/ccd/polytope.h \
   $$PWD/rai/rai/Geo/ccd/quat.h \
   $$PWD/rai/rai/Geo/ccd/simplex.h \
   $$PWD/rai/rai/Geo/ccd/support.h \
   $$PWD/rai/rai/Geo/ccd/vec3.h \
   $$PWD/rai/rai/Geo/GJK/gjk.h \
   $$PWD/rai/rai/Geo/Lewiner/LookUpTable.h \
   $$PWD/rai/rai/Geo/Lewiner/MarchingCubes.h \
   $$PWD/rai/rai/Geo/ply/ply.h \
   $$PWD/rai/rai/Geo/fcl.h \
   $$PWD/rai/rai/Geo/fclInterface.h \
   $$PWD/rai/rai/Geo/geo.h \
   $$PWD/rai/rai/Geo/geoms.h \
   $$PWD/rai/rai/Geo/mesh.h \
   $$PWD/rai/rai/Geo/mesh_readAssimp.h \
   $$PWD/rai/rai/Geo/pairCollision.h \
   $$PWD/rai/rai/Geo/qhull.h \
   $$PWD/rai/rai/Geo/stb_image.h \
   $$PWD/rai/rai/GeoOptim/geoOptim.h \
   $$PWD/rai/rai/Gui/retired/opengl_qt.h \
   $$PWD/rai/rai/Gui/color.h \
   $$PWD/rai/rai/Gui/graphview.h \
   $$PWD/rai/rai/Gui/gtk.h \
   $$PWD/rai/rai/Gui/opengl.h \
   $$PWD/rai/rai/Gui/viewer.h \
   $$PWD/rai/rai/Kin/retired/F_pushed.h \
   $$PWD/rai/rai/Kin/retired/F_retired.h \
   $$PWD/rai/rai/Kin/retired/flag.h \
   $$PWD/rai/rai/Kin/retired/ors_actionInterface.h \
   $$PWD/rai/rai/Kin/retired/ors_oldTaskVariables.h \
   $$PWD/rai/rai/Kin/retired/ors_sceneGui.h \
   $$PWD/rai/rai/Kin/retired/ors_tutorial.h \
   $$PWD/rai/rai/Kin/retired/roboticsCourse.h \
   $$PWD/rai/rai/Kin/retired/taskMaps.h \
   $$PWD/rai/rai/Kin/retired/TM_AlignStacking.h \
   $$PWD/rai/rai/Kin/retired/TM_FixSwitchedObjects.h \
   $$PWD/rai/rai/Kin/retired/TM_FlagConstraints.h \
   $$PWD/rai/rai/Kin/retired/TM_GJK.h \
   $$PWD/rai/rai/Kin/retired/TM_gravity.h \
   $$PWD/rai/rai/Kin/retired/TM_ImpulseExchange.h \
   $$PWD/rai/rai/Kin/retired/TM_InertialMotion.h \
   $$PWD/rai/rai/Kin/retired/TM_linTrans.h \
   $$PWD/rai/rai/Kin/retired/TM_pushConsistent.h \
   $$PWD/rai/rai/Kin/retired/TM_qLimits.h \
   $$PWD/rai/rai/Kin/retired/TM_QuaternionNorms.h \
   $$PWD/rai/rai/Kin/retired/TM_transition.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_array.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_boxnode.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_common.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_config.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_fileio.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_front.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_linalg.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_lut.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_mesh.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_mesh_utils.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_object.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_pair.h \
   $$PWD/rai/rai/Kin/SWIFT/SWIFT_pqueue.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/matvec.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/moments.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/obb.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/overlap.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/RAPID.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/RAPID_private.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/RAPID_version.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/convex.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/cvxutils.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/gui.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/guidraw.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/io.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/tk8.4a3.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/togl.h \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/viewer.h \
   $$PWD/rai/rai/Kin/cameraview.h \
   $$PWD/rai/rai/Kin/contact.h \
   $$PWD/rai/rai/Kin/F_contacts.h \
   $$PWD/rai/rai/Kin/F_dynamics.h \
   $$PWD/rai/rai/Kin/F_geometrics.h \
   $$PWD/rai/rai/Kin/F_operators.h \
   $$PWD/rai/rai/Kin/F_PairCollision.h \
   $$PWD/rai/rai/Kin/F_pose.h \
   $$PWD/rai/rai/Kin/F_qFeatures.h \
   $$PWD/rai/rai/Kin/F_static.h \
   $$PWD/rai/rai/Kin/feature.h \
   $$PWD/rai/rai/Kin/featureSymbols.h \
   $$PWD/rai/rai/Kin/frame.h \
   $$PWD/rai/rai/Kin/kin.h \
   $$PWD/rai/rai/Kin/kin_bullet.h \
   $$PWD/rai/rai/Kin/kin_feather.h \
   $$PWD/rai/rai/Kin/kin_ode.h \
   $$PWD/rai/rai/Kin/kin_physx.h \
   $$PWD/rai/rai/Kin/kin_swift.h \
   $$PWD/rai/rai/Kin/kinViewer.h \
   $$PWD/rai/rai/Kin/PhysXThread.h \
   $$PWD/rai/rai/Kin/proxy.h \
   $$PWD/rai/rai/Kin/simulation.h \
   $$PWD/rai/rai/Kin/switch.h \
   $$PWD/rai/rai/Kin/TM_angVel.h \
   $$PWD/rai/rai/Kin/TM_BeliefTransition.h \
   $$PWD/rai/rai/Kin/TM_default.h \
   $$PWD/rai/rai/Kin/TM_proxy.h \
   $$PWD/rai/rai/Kin/TM_qUncertainties.h \
   $$PWD/rai/rai/Kin/TM_time.h \
   $$PWD/rai/rai/Kin/uncertainty.h \
   $$PWD/rai/rai/KOMO/retired/adaptiveMotionExecution.h \
   $$PWD/rai/rai/KOMO/retired/benchmarks.h \
   $$PWD/rai/rai/KOMO/retired/motion-15-12-10.h \
   $$PWD/rai/rai/KOMO/retired/motion-17-04-05.h \
   $$PWD/rai/rai/KOMO/retired/motionHeuristics.h \
   $$PWD/rai/rai/KOMO/retired/phase_optimization.h \
   $$PWD/rai/rai/KOMO/retired/pr2_heuristics.h \
   $$PWD/rai/rai/KOMO/retired/rrt_planner.h \
   $$PWD/rai/rai/KOMO/retired/taskMap_default.h \
   $$PWD/rai/rai/KOMO/komo-ext.h \
   $$PWD/rai/rai/KOMO/komo.h \
   $$PWD/rai/rai/KOMO/objective.h \
   $$PWD/rai/rai/KOMO/pathTools.h \
   $$PWD/rai/rai/LGP/retired/effectivePoseProblem.h \
   $$PWD/rai/rai/LGP/retired/LGP.h \
   $$PWD/rai/rai/LGP/retired/pathProblem.h \
   $$PWD/rai/rai/LGP/retired/towerProblem.h \
   $$PWD/rai/rai/LGP/bounds.h \
   $$PWD/rai/rai/LGP/LGP_node.h \
   $$PWD/rai/rai/LGP/LGP_tree.h \
   $$PWD/rai/rai/Logic/fol.h \
   $$PWD/rai/rai/Logic/fol_mcts_world.h \
   $$PWD/rai/rai/Logic/relationalMachine.h \
   $$PWD/rai/rai/MCTS/env_robert.h \
   $$PWD/rai/rai/MCTS/environment.h \
   $$PWD/rai/rai/MCTS/problem_BlindBranch.h \
   $$PWD/rai/rai/MCTS/solver_AStar.h \
   $$PWD/rai/rai/MCTS/solver_marc.h \
   $$PWD/rai/rai/MCTS/solver_MBTS.h \
   $$PWD/rai/rai/MCTS/solver_PlainMC.h \
   $$PWD/rai/rai/Operate/op.h \
   $$PWD/rai/rai/Operate/path.h \
   $$PWD/rai/rai/Operate/robot_pr2.h \
   $$PWD/rai/rai/Operate/robotio.h \
   $$PWD/rai/rai/Operate/robotOperation.h \
   $$PWD/rai/rai/Operate/simulation.h \
   $$PWD/rai/rai/Operate/simulationThread.h \
   $$PWD/rai/rai/Operate/splineRunner.h \
   $$PWD/rai/rai/Optim/retired/benchmarks.h \
   $$PWD/rai/rai/Optim/retired/blackbox.h \
   $$PWD/rai/rai/Optim/retired/blackbox2.h \
   $$PWD/rai/rai/Optim/retired/kOrderMarkov.h \
   $$PWD/rai/rai/Optim/retired/opt-constrainedOld.h \
   $$PWD/rai/rai/Optim/retired/optimization_obsolete.h \
   $$PWD/rai/rai/Optim/BayesOpt.h \
   $$PWD/rai/rai/Optim/benchmarks.h \
   $$PWD/rai/rai/Optim/constrained.h \
   $$PWD/rai/rai/Optim/convert.h \
   $$PWD/rai/rai/Optim/GlobalIterativeNewton.h \
   $$PWD/rai/rai/Optim/gradient.h \
   $$PWD/rai/rai/Optim/Graph_Problem.h \
   $$PWD/rai/rai/Optim/GraphOptim.h \
   $$PWD/rai/rai/Optim/KOMO_Problem.h \
   $$PWD/rai/rai/Optim/lagrangian.h \
   $$PWD/rai/rai/Optim/newton.h \
   $$PWD/rai/rai/Optim/optimization.h \
   $$PWD/rai/rai/Optim/primalDual.h \
   $$PWD/rai/rai/Optim/RidgeRegression.h \
   $$PWD/rai/rai/Perception/retired/module_VideoWriter.h \
   $$PWD/rai/rai/Perception/retired/plane.h \
   $$PWD/rai/rai/Perception/retired/pointcloud.h \
   $$PWD/rai/rai/Perception/audio.h \
   $$PWD/rai/rai/Perception/avutil.h \
   $$PWD/rai/rai/Perception/colorseg.h \
   $$PWD/rai/rai/Perception/dataStructures.h \
   $$PWD/rai/rai/Perception/depth2PointCloud.h \
   $$PWD/rai/rai/Perception/depth_packing.h \
   $$PWD/rai/rai/Perception/filter.h \
   $$PWD/rai/rai/Perception/g4data.h \
   $$PWD/rai/rai/Perception/kinect2pointCloud.h \
   $$PWD/rai/rai/Perception/minEigModel.h \
   $$PWD/rai/rai/Perception/modelEnsemble.h \
   $$PWD/rai/rai/Perception/object.h \
   $$PWD/rai/rai/Perception/object_detector.h \
   $$PWD/rai/rai/Perception/opencv.h \
   $$PWD/rai/rai/Perception/opencvCamera.h \
   $$PWD/rai/rai/Perception/pcl.h \
   $$PWD/rai/rai/Perception/pclPlaneExtraction.h \
   $$PWD/rai/rai/Perception/percept.h \
   $$PWD/rai/rai/Perception/perception.h \
   $$PWD/rai/rai/Perception/perceptSyncer.h \
   $$PWD/rai/rai/Perception/perceptViewer.h \
   $$PWD/rai/rai/Perception/pixel_format.h \
   $$PWD/rai/rai/Perception/pointcloud_io.h \
   $$PWD/rai/rai/Perception/shapeFitter.h \
   $$PWD/rai/rai/Perception/surfels.h \
   $$PWD/rai/rai/Perception/videoEncoder.h \
   $$PWD/rai/rai/Plot/plot.h \
   $$PWD/rai/rai/rai_msgs/baxter/EndEffectorCommand.h \
   $$PWD/rai/rai/rai_msgs/baxter/EndEffectorState.h \
   $$PWD/rai/rai/rai_msgs/baxter/HeadPanCommand.h \
   $$PWD/rai/rai/rai_msgs/baxter/JointCommand.h \
   $$PWD/rai/rai/rai_msgs/retired/Literal.h \
   $$PWD/rai/rai/rai_msgs/retired/MarkerArray.h \
   $$PWD/rai/rai/rai_msgs/retired/ObjId.h \
   $$PWD/rai/rai/rai_msgs/retired/StringString.h \
   $$PWD/rai/rai/rai_msgs/retired/StringStringRequest.h \
   $$PWD/rai/rai/rai_msgs/retired/StringStringResponse.h \
   $$PWD/rai/rai/rai_msgs/arr.h \
   $$PWD/rai/rai/rai_msgs/JointState.h \
   $$PWD/rai/rai/rai_msgs/MotionCompliance.h \
   $$PWD/rai/rai/rai_msgs/MotionFeedback.h \
   $$PWD/rai/rai/rai_msgs/MotionReference.h \
   $$PWD/rai/rai/rai_msgs/SendJointTrajectory.h \
   $$PWD/rai/rai/rai_msgs/SendJointTrajectoryRequest.h \
   $$PWD/rai/rai/rai_msgs/SendJointTrajectoryResponse.h \
   $$PWD/rai/rai/rai_msgs/StringA.h \
   $$PWD/rai/rai/rai_msgs/StringString.h \
   $$PWD/rai/rai/rai_msgs/StringStringRequest.h \
   $$PWD/rai/rai/rai_msgs/StringStringResponse.h \
   $$PWD/rai/rai/rai_msgs/WSG_50_command.h \
   $$PWD/rai/rai/rai_msgs/WSG_50_state.h \
   $$PWD/rai/rai/RosCom/perc/perceptionCollection.h \
   $$PWD/rai/rai/RosCom/perc/publishDatabase.h \
   $$PWD/rai/rai/RosCom/perc/subscribeAlvarMarkers.h \
   $$PWD/rai/rai/RosCom/perc/subscribeFingerPressures.h \
   $$PWD/rai/rai/RosCom/perc/subscribeLaserScan.h \
   $$PWD/rai/rai/RosCom/perc/subscribeOptitrack.h \
   $$PWD/rai/rai/RosCom/perc/subscribeRosKinect.h \
   $$PWD/rai/rai/RosCom/perc/subscribeRosKinect2PCL.h \
   $$PWD/rai/rai/RosCom/perc/subscribeTableArray.h \
   $$PWD/rai/rai/RosCom/perc/subscribeTabletop.h \
   $$PWD/rai/rai/RosCom/rai_msgs/baxter/EndEffectorCommand.h \
   $$PWD/rai/rai/RosCom/rai_msgs/baxter/EndEffectorState.h \
   $$PWD/rai/rai/RosCom/rai_msgs/baxter/HeadPanCommand.h \
   $$PWD/rai/rai/RosCom/rai_msgs/baxter/JointCommand.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/Literal.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/MarkerArray.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/ObjId.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/StringString.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/StringStringRequest.h \
   $$PWD/rai/rai/RosCom/rai_msgs/retired/StringStringResponse.h \
   $$PWD/rai/rai/RosCom/rai_msgs/arr.h \
   $$PWD/rai/rai/RosCom/rai_msgs/JointState.h \
   $$PWD/rai/rai/RosCom/rai_msgs/MotionCompliance.h \
   $$PWD/rai/rai/RosCom/rai_msgs/MotionFeedback.h \
   $$PWD/rai/rai/RosCom/rai_msgs/MotionReference.h \
   $$PWD/rai/rai/RosCom/rai_msgs/SendJointTrajectory.h \
   $$PWD/rai/rai/RosCom/rai_msgs/SendJointTrajectoryRequest.h \
   $$PWD/rai/rai/RosCom/rai_msgs/SendJointTrajectoryResponse.h \
   $$PWD/rai/rai/RosCom/rai_msgs/StringA.h \
   $$PWD/rai/rai/RosCom/rai_msgs/StringString.h \
   $$PWD/rai/rai/RosCom/rai_msgs/StringStringRequest.h \
   $$PWD/rai/rai/RosCom/rai_msgs/StringStringResponse.h \
   $$PWD/rai/rai/RosCom/rai_msgs/WSG_50_command.h \
   $$PWD/rai/rai/RosCom/rai_msgs/WSG_50_state.h \
   $$PWD/rai/rai/RosCom/retired/pr2Interface.h \
   $$PWD/rai/rai/RosCom/retired/roscom.h \
   $$PWD/rai/rai/RosCom/retired/rosmacro.h \
   $$PWD/rai/rai/RosCom/retired/serviceRAP.h \
   $$PWD/rai/rai/RosCom/retired/trajectoryInterface.h \
   $$PWD/rai/rai/RosCom/baxter.h \
   $$PWD/rai/rai/RosCom/image_pub.h \
   $$PWD/rai/rai/RosCom/rosCamera.h \
   $$PWD/rai/rai/RosCom/roscom.h \
   $$PWD/rai/rai/RosCom/spinner.h \
   $$PWD/rai/rai/ry/lgp-py.h \
   $$PWD/rai/rai/ry/ry.h \
   $$PWD/rai/test/Optim/constrained/problems.h \
   $$PWD/rai/rai/KOMO/restserver.h

SOURCES = \
   $$PWD/rai/bin/src_gView/main.cpp \
   $$PWD/rai/bin/src_kinEdit/main.cpp \
   $$PWD/rai/bin/src_meshTool/main.cpp \
   $$PWD/rai/rai/Algo/algos.cpp \
   $$PWD/rai/rai/Algo/ann.cpp \
   $$PWD/rai/rai/Algo/astar.cpp \
   $$PWD/rai/rai/Algo/cma.cpp \
   $$PWD/rai/rai/Algo/dataNeighbored.cpp \
   $$PWD/rai/rai/Algo/eigenValues.cpp \
   $$PWD/rai/rai/Algo/gaussianProcess.cpp \
   $$PWD/rai/rai/Algo/gaussianProcess_plot.cpp \
   $$PWD/rai/rai/Algo/gpOp.cpp \
   $$PWD/rai/rai/Algo/hungarian.cpp \
   $$PWD/rai/rai/Algo/kalman.cpp \
   $$PWD/rai/rai/Algo/MLcourse.cpp \
   $$PWD/rai/rai/Algo/priorityQueue.cpp \
   $$PWD/rai/rai/Algo/rrt.cpp \
   $$PWD/rai/rai/Algo/spline.cpp \
   $$PWD/rai/rai/Control/retired/dynamicMovementPrimitives.cpp \
   $$PWD/rai/rai/Control/retired/GamepadControlThread.cpp \
   $$PWD/rai/rai/Control/retired/taskControl-18-09-06.cpp \
   $$PWD/rai/rai/Control/retired/taskController-17-02-09.cpp \
   $$PWD/rai/rai/Control/retired/TaskControllerModule-17-02-10.cpp \
   $$PWD/rai/rai/Control/retired/taskSpaceController_danny.cpp \
   $$PWD/rai/rai/Control/gamepad2tasks.cpp \
   $$PWD/rai/rai/Control/gravityCompensation.cpp \
   $$PWD/rai/rai/Control/RTControllerSimulation.cpp \
   $$PWD/rai/rai/Control/taskControl.cpp \
   $$PWD/rai/rai/Control/TaskControlThread.cpp \
   $$PWD/rai/rai/Control/teleop2tasks.cpp \
   $$PWD/rai/rai/Core/retired/algos.cpp \
   $$PWD/rai/rai/Core/retired/algos_LU.cpp \
   $$PWD/rai/rai/Core/retired/array.cpp \
   $$PWD/rai/rai/Core/retired/array_instantiate.cxx \
   $$PWD/rai/rai/Core/retired/module.cpp \
   $$PWD/rai/rai/Core/retired/qt_integration.cpp \
   $$PWD/rai/rai/Core/retired/types.cpp \
   $$PWD/rai/rai/Core/retired/util.cpp \
   $$PWD/rai/rai/Core/array.cpp \
   $$PWD/rai/rai/Core/graph.cpp \
   $$PWD/rai/rai/Core/thread.cpp \
   $$PWD/rai/rai/Core/util.cpp \
   $$PWD/rai/rai/Geo/ccd/ccd.c \
   $$PWD/rai/rai/Geo/ccd/mpr.c \
   $$PWD/rai/rai/Geo/ccd/polytope.c \
   $$PWD/rai/rai/Geo/ccd/support.c \
   $$PWD/rai/rai/Geo/ccd/vec3.c \
   $$PWD/rai/rai/Geo/GJK/org/gjkdemo.c \
   $$PWD/rai/rai/Geo/GJK/org/sac.c \
   $$PWD/rai/rai/Geo/GJK/gjk.c \
   $$PWD/rai/rai/Geo/Lewiner/MarchingCubes.cpp \
   $$PWD/rai/rai/Geo/ply/ply.c \
   $$PWD/rai/rai/Geo/fclInterface.cpp \
   $$PWD/rai/rai/Geo/geo.cpp \
   $$PWD/rai/rai/Geo/geoms.cpp \
   $$PWD/rai/rai/Geo/mesh.cpp \
   $$PWD/rai/rai/Geo/mesh_readAssimp.cpp \
   $$PWD/rai/rai/Geo/pairCollision.cpp \
   $$PWD/rai/rai/Geo/pqp_RectDist.cpp \
   $$PWD/rai/rai/Geo/qhull.cpp \
   $$PWD/rai/rai/GeoOptim/geoOptim.cpp \
   $$PWD/rai/rai/Gui/retired/opengl_fltk.cxx \
   $$PWD/rai/rai/Gui/retired/opengl_gtk.cxx \
   $$PWD/rai/rai/Gui/retired/opengl_qt.cxx \
   $$PWD/rai/rai/Gui/retired/opengl_qt_moc.cxx \
   $$PWD/rai/rai/Gui/retired/opengl_void.cxx \
   $$PWD/rai/rai/Gui/graphview.cpp \
   $$PWD/rai/rai/Gui/gtk.cpp \
   $$PWD/rai/rai/Gui/opengl.cpp \
   $$PWD/rai/rai/Gui/viewer.cpp \
   $$PWD/rai/rai/Kin/retired/contact-18-03-09.cpp \
   $$PWD/rai/rai/Kin/retired/F_pushed.cpp \
   $$PWD/rai/rai/Kin/retired/F_retired.cpp \
   $$PWD/rai/rai/Kin/retired/flag.cpp \
   $$PWD/rai/rai/Kin/retired/ors.cpp \
   $$PWD/rai/rai/Kin/retired/ors_actionInterface.cpp \
   $$PWD/rai/rai/Kin/retired/ors_blender.cpp \
   $$PWD/rai/rai/Kin/retired/ors_featherstone.cpp \
   $$PWD/rai/rai/Kin/retired/ors_oldTaskVariables.cpp \
   $$PWD/rai/rai/Kin/retired/ors_opengl.cpp \
   $$PWD/rai/rai/Kin/retired/ors_sceneGui.cpp \
   $$PWD/rai/rai/Kin/retired/ors_tutorial.cxx \
   $$PWD/rai/rai/Kin/retired/roboticsCourse.cpp \
   $$PWD/rai/rai/Kin/retired/switch.cpp \
   $$PWD/rai/rai/Kin/retired/taskMap.cpp \
   $$PWD/rai/rai/Kin/retired/taskMaps_constrained.cpp \
   $$PWD/rai/rai/Kin/retired/TM_AlignStacking.cpp \
   $$PWD/rai/rai/Kin/retired/TM_FixSwitchedObjects.cpp \
   $$PWD/rai/rai/Kin/retired/TM_FlagConstraints.cpp \
   $$PWD/rai/rai/Kin/retired/TM_GJK.cpp \
   $$PWD/rai/rai/Kin/retired/TM_gravity.cpp \
   $$PWD/rai/rai/Kin/retired/TM_ImpulseExchange.cpp \
   $$PWD/rai/rai/Kin/retired/TM_InertialMotion.cpp \
   $$PWD/rai/rai/Kin/retired/TM_linTrans.cpp \
   $$PWD/rai/rai/Kin/retired/TM_pushConsistent.cpp \
   $$PWD/rai/rai/Kin/retired/TM_qLimits.cpp \
   $$PWD/rai/rai/Kin/retired/TM_QuaternionNorms.cpp \
   $$PWD/rai/rai/Kin/retired/TM_transition.cpp \
   $$PWD/rai/rai/Kin/SWIFT/fileio.cpp \
   $$PWD/rai/rai/Kin/SWIFT/lut.cpp \
   $$PWD/rai/rai/Kin/SWIFT/mesh.cpp \
   $$PWD/rai/rai/Kin/SWIFT/mesh_utils.cpp \
   $$PWD/rai/rai/Kin/SWIFT/object.cpp \
   $$PWD/rai/rai/Kin/SWIFT/pair.cpp \
   $$PWD/rai/rai/Kin/SWIFT/pqueue.cpp \
   $$PWD/rai/rai/Kin/SWIFT/scene.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/build.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/collide.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/overlap.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID/RAPID.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/convex.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/cvxutils.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/gui.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/guidraw.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/io.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/main.cxx \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/togl.cpp \
   $$PWD/rai/rai/Kin/SWIFT_decomposer/viewer.cpp \
   $$PWD/rai/rai/Kin/cameraview.cpp \
   $$PWD/rai/rai/Kin/contact.cpp \
   $$PWD/rai/rai/Kin/F_contacts.cpp \
   $$PWD/rai/rai/Kin/F_dynamics.cpp \
   $$PWD/rai/rai/Kin/F_geometrics.cpp \
   $$PWD/rai/rai/Kin/F_operators.cpp \
   $$PWD/rai/rai/Kin/F_PairCollision.cpp \
   $$PWD/rai/rai/Kin/F_pose.cpp \
   $$PWD/rai/rai/Kin/F_qFeatures.cpp \
   $$PWD/rai/rai/Kin/F_static.cpp \
   $$PWD/rai/rai/Kin/feature.cpp \
   $$PWD/rai/rai/Kin/featureSymbols.cpp \
   $$PWD/rai/rai/Kin/frame.cpp \
   $$PWD/rai/rai/Kin/kin.cpp \
   $$PWD/rai/rai/Kin/kin_bullet.cpp \
   $$PWD/rai/rai/Kin/kin_feather.cpp \
   $$PWD/rai/rai/Kin/kin_ode.cpp \
   $$PWD/rai/rai/Kin/kin_physx.cpp \
   $$PWD/rai/rai/Kin/kin_swift.cpp \
   $$PWD/rai/rai/Kin/kinViewer.cpp \
   $$PWD/rai/rai/Kin/PhysXThread.cpp \
   $$PWD/rai/rai/Kin/proxy.cpp \
   $$PWD/rai/rai/Kin/simulation.cpp \
   $$PWD/rai/rai/Kin/switch.cpp \
   $$PWD/rai/rai/Kin/TM_angVel.cpp \
   $$PWD/rai/rai/Kin/TM_BeliefTransition.cpp \
   $$PWD/rai/rai/Kin/TM_default.cpp \
   $$PWD/rai/rai/Kin/TM_proxy.cpp \
   $$PWD/rai/rai/Kin/TM_qUncertainties.cpp \
   $$PWD/rai/rai/Kin/TM_time.cpp \
   $$PWD/rai/rai/Kin/uncertainty.cpp \
   $$PWD/rai/rai/KOMO/retired/adaptiveMotionExecution.cpp \
   $$PWD/rai/rai/KOMO/retired/benchmarks.cpp \
   $$PWD/rai/rai/KOMO/retired/komo-17-04-05.cpp \
   $$PWD/rai/rai/KOMO/retired/komo-18-01-04.cpp \
   $$PWD/rai/rai/KOMO/retired/komo_old_setGraspPlace.cpp \
   $$PWD/rai/rai/KOMO/retired/motion-15-06-10.cpp \
   $$PWD/rai/rai/KOMO/retired/motion-15-12-10.cpp \
   $$PWD/rai/rai/KOMO/retired/motion-17-04-05.cpp \
   $$PWD/rai/rai/KOMO/retired/motion.cpp \
   $$PWD/rai/rai/KOMO/retired/motionHeuristics.cpp \
   $$PWD/rai/rai/KOMO/retired/phase_optimization.cpp \
   $$PWD/rai/rai/KOMO/retired/pr2_heuristics.cpp \
   $$PWD/rai/rai/KOMO/retired/rrt_planner.cpp \
   $$PWD/rai/rai/KOMO/retired/task.cpp \
   $$PWD/rai/rai/KOMO/retired/taskMap_default.cpp \
   $$PWD/rai/rai/KOMO/komo-ext.cpp \
   $$PWD/rai/rai/KOMO/komo.cpp \
   $$PWD/rai/rai/KOMO/objective.cpp \
   $$PWD/rai/rai/KOMO/pathTools.cpp \
   $$PWD/rai/rai/LGP/retired/effectivePoseProblem.cpp \
   $$PWD/rai/rai/LGP/retired/manipulationTree.cpp \
   $$PWD/rai/rai/LGP/retired/pathProblem.cpp \
   $$PWD/rai/rai/LGP/retired/search.cpp \
   $$PWD/rai/rai/LGP/retired/towerProblem.cpp \
   $$PWD/rai/rai/LGP/bounds.cpp \
   $$PWD/rai/rai/LGP/LGP_node.cpp \
   $$PWD/rai/rai/LGP/LGP_tree.cpp \
   $$PWD/rai/rai/Logic/retired/fol.cpp \
   $$PWD/rai/rai/Logic/fol.cpp \
   $$PWD/rai/rai/Logic/fol_mcts_world.cpp \
   $$PWD/rai/rai/Logic/relationalMachine.cpp \
   $$PWD/rai/rai/MCTS/environment.cpp \
   $$PWD/rai/rai/MCTS/problem_BlindBranch.cpp \
   $$PWD/rai/rai/MCTS/solver_AStar.cpp \
   $$PWD/rai/rai/MCTS/solver_marc.cpp \
   $$PWD/rai/rai/MCTS/solver_MBTS.cxx \
   $$PWD/rai/rai/MCTS/solver_PlainMC.cpp \
   $$PWD/rai/rai/Operate/op.cpp \
   $$PWD/rai/rai/Operate/path.cpp \
   $$PWD/rai/rai/Operate/robot_pr2.cpp \
   $$PWD/rai/rai/Operate/robotio.cpp \
   $$PWD/rai/rai/Operate/robotOperation.cpp \
   $$PWD/rai/rai/Operate/simulation.cpp \
   $$PWD/rai/rai/Operate/simulationThread.cpp \
   $$PWD/rai/rai/Operate/splineRunner.cpp \
   $$PWD/rai/rai/Optim/retired/benchmarks.cpp \
   $$PWD/rai/rai/Optim/retired/blackbox.cpp \
   $$PWD/rai/rai/Optim/retired/blackbox2.cpp \
   $$PWD/rai/rai/Optim/retired/kOrderMarkov.cpp \
   $$PWD/rai/rai/Optim/retired/opt-constrainedOld.cpp \
   $$PWD/rai/rai/Optim/retired/opt-convert-15-12-10.cpp \
   $$PWD/rai/rai/Optim/retired/opt-newton.cpp \
   $$PWD/rai/rai/Optim/retired/optimization_obsolete.cxx \
   $$PWD/rai/rai/Optim/BayesOpt.cpp \
   $$PWD/rai/rai/Optim/benchmarks.cpp \
   $$PWD/rai/rai/Optim/constrained.cpp \
   $$PWD/rai/rai/Optim/convert.cpp \
   $$PWD/rai/rai/Optim/GlobalIterativeNewton.cpp \
   $$PWD/rai/rai/Optim/gradient.cpp \
   $$PWD/rai/rai/Optim/Graph_Problem.cpp \
   $$PWD/rai/rai/Optim/GraphOptim.cpp \
   $$PWD/rai/rai/Optim/KOMO_Problem.cpp \
   $$PWD/rai/rai/Optim/lagrangian.cpp \
   $$PWD/rai/rai/Optim/newton.cpp \
   $$PWD/rai/rai/Optim/optimization.cpp \
   $$PWD/rai/rai/Optim/primalDual.cpp \
   $$PWD/rai/rai/Optim/RidgeRegression.cpp \
   $$PWD/rai/rai/Perception/retired/module_VideoWriter.cpp \
   $$PWD/rai/rai/Perception/retired/plane.cpp \
   $$PWD/rai/rai/Perception/retired/pointcloud.cpp \
   $$PWD/rai/rai/Perception/retired/roopi_Perception.cpp \
   $$PWD/rai/rai/Perception/retired/videoEncoderX264.cpp \
   $$PWD/rai/rai/Perception/audio.cpp \
   $$PWD/rai/rai/Perception/avutil.cpp \
   $$PWD/rai/rai/Perception/colorseg.cpp \
   $$PWD/rai/rai/Perception/dataStructures.cpp \
   $$PWD/rai/rai/Perception/depth2PointCloud.cpp \
   $$PWD/rai/rai/Perception/depth_packing.cpp \
   $$PWD/rai/rai/Perception/filter.cpp \
   $$PWD/rai/rai/Perception/g4data.cpp \
   $$PWD/rai/rai/Perception/kinect2pointCloud.cpp \
   $$PWD/rai/rai/Perception/minEigModel.cpp \
   $$PWD/rai/rai/Perception/modelEnsemble.cpp \
   $$PWD/rai/rai/Perception/object.cpp \
   $$PWD/rai/rai/Perception/object_detector.cpp \
   $$PWD/rai/rai/Perception/opencv.cpp \
   $$PWD/rai/rai/Perception/opencvCamera.cpp \
   $$PWD/rai/rai/Perception/pcl.cpp \
   $$PWD/rai/rai/Perception/pclPlaneExtraction.cpp \
   $$PWD/rai/rai/Perception/percept.cpp \
   $$PWD/rai/rai/Perception/perception.cpp \
   $$PWD/rai/rai/Perception/perception_views.cpp \
   $$PWD/rai/rai/Perception/perceptSyncer.cpp \
   $$PWD/rai/rai/Perception/perceptViewer.cpp \
   $$PWD/rai/rai/Perception/pointcloud_io.cpp \
   $$PWD/rai/rai/Perception/shapeFitter.cpp \
   $$PWD/rai/rai/Perception/surfels.cpp \
   $$PWD/rai/rai/Perception/video_opencv.cpp \
   $$PWD/rai/rai/Perception/videoEncoder.cpp \
   $$PWD/rai/rai/Plot/plot.cpp \
   $$PWD/rai/rai/RosCom/perc/perceptionCollection.cpp \
   $$PWD/rai/rai/RosCom/perc/publishDatabase.cpp \
   $$PWD/rai/rai/RosCom/perc/subscribeAlvarMarkers.cpp \
   $$PWD/rai/rai/RosCom/perc/subscribeOptitrack.cpp \
   $$PWD/rai/rai/RosCom/perc/subscribeRosKinect2PCL.cpp \
   $$PWD/rai/rai/RosCom/retired/pr2Interface.cpp \
   $$PWD/rai/rai/RosCom/retired/roscom.cpp \
   $$PWD/rai/rai/RosCom/retired/serviceRAP.cpp \
   $$PWD/rai/rai/RosCom/retired/trajectoryInterface.cpp \
   $$PWD/rai/rai/RosCom/baxter.cpp \
   $$PWD/rai/rai/RosCom/image_pub.cpp \
   $$PWD/rai/rai/RosCom/rosCamera.cpp \
   $$PWD/rai/rai/RosCom/roscom.cpp \
   $$PWD/rai/rai/RosCom/spinner.cpp \
   $$PWD/rai/rai/ry/lgp-py.cpp \
   $$PWD/rai/rai/ry/ry.cpp \
   $$PWD/rai/test/Algo/ann/main.cpp \
   $$PWD/rai/test/Algo/ML-regression/main.cpp \
   $$PWD/rai/test/Algo/splines/main.cpp \
   $$PWD/rai/test/Core/array/main.cpp \
   $$PWD/rai/test/Core/graph/main.cpp \
   $$PWD/rai/test/Core/thread/main.cpp \
   $$PWD/rai/test/Core/util/main.cpp \
   $$PWD/rai/test/Geo/convex/main.cpp \
   $$PWD/rai/test/Geo/geo/main.cpp \
   $$PWD/rai/test/Geo/mesh/main.cpp \
   $$PWD/rai/test/Gui/opengl/main-textureExample.cpp \
   $$PWD/rai/test/Gui/opengl/main.cpp \
   $$PWD/rai/test/Gui/opengl_mini/main.cpp \
   $$PWD/rai/test/Gui/opengl_threaded/main.cpp \
   $$PWD/rai/test/Gui/opengl_windowless/egl-org.cpp \
   $$PWD/rai/test/Gui/opengl_windowless/egl.cpp \
   $$PWD/rai/test/Gui/opengl_windowless/main.cpp \
   $$PWD/rai/test/Gui/opengl_windowless/org.cpp \
   $$PWD/rai/test/Gui/projections/main.cpp \
   $$PWD/rai/test/Kin/assimp/main.cpp \
   $$PWD/rai/test/Kin/CameraView/main.cpp \
   $$PWD/rai/test/Kin/dynamics/main.cpp \
   $$PWD/rai/test/Kin/features/main.cpp \
   $$PWD/rai/test/Kin/getRobotMask/main.cpp \
   $$PWD/rai/test/Kin/kin/main.cpp \
   $$PWD/rai/test/Kin/pairCollision_jacobians/main.cpp \
   $$PWD/rai/test/Kin/physx/main.cpp \
   $$PWD/rai/test/Kin/SSB_distance/main.cpp \
   $$PWD/rai/test/Kin/swift/meshTools/main.cpp \
   $$PWD/rai/test/Kin/swift/main.cpp \
   $$PWD/rai/test/KOMO/komo/main.cpp \
   $$PWD/rai/test/KOMO/retired/impulse/main.cpp \
   $$PWD/rai/test/KOMO/seq/main.cpp \
   $$PWD/rai/test/KOMO/switches/main.cpp \
   $$PWD/rai/test/KOMO/tutorial/main.cpp \
   $$PWD/rai/test/LGP/pickAndPlace/main.cpp \
   $$PWD/rai/test/Logic/fol/main.cpp \
   $$PWD/rai/test/Logic/pddl/main.cpp \
   $$PWD/rai/test/Logic/player/main.cpp \
   $$PWD/rai/test/Logic/relationalMachine/main.cpp \
   $$PWD/rai/test/Optim/constrained/lecture.cpp \
   $$PWD/rai/test/Optim/constrained/main.cpp \
   $$PWD/rai/test/Optim/Graph_problem/main.cpp \
   $$PWD/rai/test/Optim/KOMO_problem/main.cpp \
   $$PWD/rai/test/Optim/optim/main.cpp \
   $$PWD/test/komo/main.cpp \
   $$PWD/test/seq/main.cpp \
   $$PWD/test/tutorial/main.cpp \
   $$PWD/rai/rai/KOMO/restserver.cpp \
   $$PWD/demo/main.cpp

INCLUDEPATH = \
    $$PWD/rai/rai/Algo \
    $$PWD/rai/rai/Control \
    $$PWD/rai/rai/Control/retired \
    $$PWD/rai/rai/Core \
    $$PWD/rai/rai/Core/lapack \
    $$PWD/rai/rai/Core/retired \
    $$PWD/rai/rai/Geo \
    $$PWD/rai/rai/Geo/ccd \
    $$PWD/rai/rai/Geo/GJK \
    $$PWD/rai/rai/Geo/Lewiner \
    $$PWD/rai/rai/Geo/ply \
    $$PWD/rai/rai/GeoOptim \
    $$PWD/rai/rai/Gui \
    $$PWD/rai/rai/Gui/retired \
    $$PWD/rai/rai/Kin \
    $$PWD/rai/rai/Kin/retired \
    $$PWD/rai/rai/Kin/SWIFT \
    $$PWD/rai/rai/Kin/SWIFT_decomposer \
    $$PWD/rai/rai/Kin/SWIFT_decomposer/RAPID \
    $$PWD/rai/rai/KOMO \
    $$PWD/rai/rai/KOMO/retired \
    $$PWD/rai/rai/LGP \
    $$PWD/rai/rai/LGP/retired \
    $$PWD/rai/rai/Logic \
    $$PWD/rai/rai/MCTS \
    $$PWD/rai/rai/Operate \
    $$PWD/rai/rai/Optim \
    $$PWD/rai/rai/Optim/retired \
    $$PWD/rai/rai/Perception \
    $$PWD/rai/rai/Perception/retired \
    $$PWD/rai/rai/Plot \
    $$PWD/rai/rai/rai_msgs \
    $$PWD/rai/rai/rai_msgs/baxter \
    $$PWD/rai/rai/rai_msgs/retired \
    $$PWD/rai/rai/RosCom \
    $$PWD/rai/rai/RosCom/perc \
    $$PWD/rai/rai/RosCom/rai_msgs \
    $$PWD/rai/rai/RosCom/rai_msgs/baxter \
    $$PWD/rai/rai/RosCom/rai_msgs/retired \
    $$PWD/rai/rai/RosCom/retired \
    $$PWD/rai/rai/ry \
    $$PWD/rai/test/Optim/constrained

INCLUDEPATH += $$PWD/rai/rai/
#DEFINES = 

